//! Reflection processor — LLM-driven metacognition with rate-limit handling.
//!
//! Periodically analyzes accumulated episodes and generates insights,
//! identity updates, and principle distillations. Uses Deep LLM tier.
//! Falls back to heuristic pattern detection when rate limited.

use std::sync::Arc;
use async_trait::async_trait;
use anyhow::Result;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tracing;

use crate::kernel::signal::{SignalArc, SignalType};
use crate::signals::types;
use crate::signals::{EpisodeRecorded, IdentityUpdated, BeliefChanged, BeliefChangeType};
use crate::processor::processor::Processor;
use crate::field_runtime::context::FieldContext;
use crate::engines::llm::{CompletionRequest, Message, ModelTier, TieredRouter};
use crate::engines::llm::types::LLMError;
use crate::engines::llm::extract::first_json;

/// Reflection system prompt — improved for better insight quality.
const REFLECTION_SYSTEM: &str = r#"You are a reflective cognition engine analyzing personal experiences.

Given a set of recent experiences, generate reflections in the following JSON format:
{
  "reflections": [
    {
      "insight": "A key realization or pattern noticed — specific and grounded in the experiences",
      "domain": "work|learning|health|relationships|creativity",
      "significance": 0.0-1.0,
      "principles": ["A principle derived from this insight"]
    }
  ]
}

Focus on:
- Recurring patterns across experiences (be specific, reference the actual topics)
- Contradictions or tensions between experiences
- Emerging principles or values
- Growth or change over time
- Topics that deserve more attention

Make insights concrete and specific. Avoid generic statements.
Maximum 3 reflections per batch.

Reply ONLY JSON, no prose.
"#;

/// A single reflection generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Reflection {
    pub insight: String,
    pub domain: String,
    pub significance: f32,
    pub principles: Vec<String>,
}

/// State of the ReflectionProcessor.
#[derive(Debug, Default, Serialize, Deserialize)]
struct ReflectionState {
    episode_count: usize,
    recent_content: Vec<String>,
    last_reflection: Option<DateTime<Utc>>,
    reflection_count: usize,
}

/// Reflection processor — generates metacognitive insights from episodes.
///
/// Uses the Deep LLM tier for reflection generation when available.
/// Falls back to heuristic pattern detection when rate limited or LLM unavailable.
pub struct ReflectionProcessor {
    state: ReflectionState,
    router: Option<TieredRouter>,
}

impl ReflectionProcessor {
    pub fn new() -> Self {
        let router = if TieredRouter::has_api_key() {
            match TieredRouter::from_env() {
                Ok(r) => Some(r),
                Err(e) => {
                    tracing::warn!("[Reflection] LLM unavailable: {}", e);
                    None
                }
            }
        } else {
            None
        };

        Self {
            state: ReflectionState::default(),
            router,
        }
    }

    /// Generate reflections using LLM (when available) or heuristics.
    async fn generate_reflections(&mut self, content: &[String]) -> Vec<Reflection> {
        if self.router.is_some() {
            let mut router = self.router.take().unwrap();
            let result = self.llm_reflect(&mut router, content).await;
            self.router = Some(router);
            match result {
                Ok(reflections) => return reflections,
                Err(e) => tracing::warn!("[Reflection] LLM failed ({}), using heuristics", e),
            }
        }
        self.heuristic_reflect(content)
    }

    /// LLM-based reflection (Deep tier) with rate-limit awareness.
    async fn llm_reflect(
        &mut self,
        router: &mut TieredRouter,
        content: &[String],
    ) -> Result<Vec<Reflection>, LLMError> {
        let text = content.join("\n");
        let request = CompletionRequest::new(
            "reflection",
            vec![
                Message::system(REFLECTION_SYSTEM),
                Message::user(&format!("Recent experiences:\n{}", text)),
            ],
        )
        .with_temperature(0.3)
        .with_max_tokens(2048);

        match router.complete(ModelTier::Deep, request).await {
            Ok(response) => {
                let result: serde_json::Value =
                    first_json(&response.content)
                        .unwrap_or(serde_json::json!({"reflections": []}));

                let reflections: Vec<Reflection> = result
                    .get("reflections")
                    .and_then(|v| serde_json::from_value(v.clone()).ok())
                    .unwrap_or_default();

                if reflections.is_empty() {
                    tracing::warn!("[Reflection] LLM returned empty reflections");
                }

                Ok(reflections)
            }
            Err(LLMError::RateLimited { retry_after }) => {
                tracing::warn!("[Reflection] rate limited ({}s), falling back to heuristics", retry_after);
                Err(LLMError::RateLimited { retry_after })
            }
            Err(e) => {
                tracing::warn!("[Reflection] LLM error: {}, falling back to heuristics", e);
                Err(e)
            }
        }
    }

    /// Heuristic reflection (no LLM needed).
    fn heuristic_reflect(&self, content: &[String]) -> Vec<Reflection> {
        let mut reflections = Vec::new();
        let mut word_counts: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
        for c in content {
            for word in c.split_whitespace() {
                let clean = word
                    .trim_matches(|c: char| !c.is_alphanumeric())
                    .to_lowercase();
                if clean.len() > 4 {
                    *word_counts.entry(clean).or_insert(0) += 1;
                }
            }
        }

        let threshold = (content.len() / 2).max(2);
        let themes: Vec<String> = word_counts
            .into_iter()
            .filter(|(_, count)| *count >= threshold)
            .take(3)
            .map(|(word, _)| word)
            .collect();

        if !themes.is_empty() {
            reflections.push(Reflection {
                insight: format!("Recurring themes detected: {}", themes.join(", ")),
                domain: "learning".to_string(),
                significance: 0.5,
                principles: vec![],
            });
        }

        reflections
    }
}

#[async_trait]
impl Processor for ReflectionProcessor {
    fn name(&self) -> &str {
        "reflection"
    }

    fn version(&self) -> &str {
        "0.1.0"
    }

    fn priority(&self) -> u8 {
        200
    }

    fn subscribed_signals(&self) -> &[SignalType] {
        &[types::EPISODE_RECORDED, types::MEMORY_CONSOLIDATED]
    }

    fn emitted_signals(&self) -> &[SignalType] {
        &[types::IDENTITY_UPDATED, types::BELIEF_CHANGED]
    }

    async fn process(
        &mut self,
        _ctx: &FieldContext,
        signal: SignalArc,
    ) -> Result<Vec<SignalArc>> {
        if let Some(ep) = signal.as_any().downcast_ref::<EpisodeRecorded>() {
            self.state.episode_count += 1;
            self.state.recent_content.push(ep.content.clone());

            // Reflect every 5 episodes
            if self.state.episode_count % 5 == 0 {
                tracing::info!(
                    "[Reflection] episode {} — generating reflections",
                    self.state.episode_count
                );

                let recent = self.state.recent_content.clone();
                let reflections = self.generate_reflections(&recent).await;
                self.state.reflection_count += reflections.len();

                let mut emitted: Vec<SignalArc> = Vec::new();

                for refl in &reflections {
                    if refl.significance > 0.6 {
                        let bc = BeliefChanged::new(
                            &refl.insight,
                            BeliefChangeType::Created,
                            refl.significance,
                        );
                        emitted.push(Arc::new(bc));
                    }

                    if self.state.reflection_count % 3 == 0 {
                        let iu = IdentityUpdated {
                            meta: signal.meta().child(types::IDENTITY_UPDATED, "reflection::processor"),
                            identity_version: (self.state.reflection_count / 3) as u32,
                            beliefs_count: reflections.len(),
                            traits_count: 0,
                            summary: refl.insight.clone(),
                        };
                        emitted.push(Arc::new(iu));
                    }
                }

                tracing::info!(
                    "[Reflection] generated {} reflection(s)",
                    reflections.len()
                );

                return Ok(emitted);
            }
        }

        Ok(vec![])
    }
}

impl Default for ReflectionProcessor {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kernel::bus::EventBus;
    use crate::kernel::signal::{Signal, SignalMeta, SignalType};
    use crate::signals::{EpisodeRecorded, MemoryConsolidated};
    use crate::storage::memory_store::MemoryStore;

    fn test_context() -> FieldContext {
        let bus = Arc::new(EventBus::new());
        let storage = Arc::new(MemoryStore::new());
        FieldContext::new(bus, storage)
    }

    #[test]
    fn test_reflection_name() {
        let p = ReflectionProcessor::new();
        assert_eq!(p.name(), "reflection");
    }

    #[test]
    fn test_reflection_subscriptions() {
        let p = ReflectionProcessor::new();
        let subs = p.subscribed_signals();
        assert!(subs.contains(&types::EPISODE_RECORDED));
        assert!(subs.contains(&types::MEMORY_CONSOLIDATED));
    }

    #[tokio::test]
    async fn test_reflection_buffers_episodes() {
        let mut p = ReflectionProcessor::new();
        let ctx = test_context();

        // Send 4 episodes — no reflection triggered (threshold is 5)
        for i in 0..4 {
            let ep = EpisodeRecorded::new(&format!("Experience number {}", i + 1), "test", vec![]);
            let result = p.process(&ctx, Arc::new(ep)).await.unwrap();
            assert!(result.is_empty(), "episodes should buffer without reflection");
        }

        assert_eq!(p.state.episode_count, 4, "should track episode count");
    }

    #[tokio::test]
    async fn test_reflection_triggers_every_5() {
        let mut p = ReflectionProcessor::new();
        let ctx = test_context();

        for i in 0..5 {
            let ep = EpisodeRecorded::new(&format!("Experience number {}", i + 1), "test", vec![]);
            // The 5th one should trigger reflection (heuristic, significance=0.5 < 0.6, so may not emit)
            let _ = p.process(&ctx, Arc::new(ep)).await.unwrap();
        }

        assert_eq!(p.state.episode_count, 5, "should have processed 5 episodes");
        assert!(p.state.reflection_count > 0 || p.state.recent_content.len() <= 5,
            "reflection should have been triggered");
    }
}
